version: "3"
services:
  springboot-app:
    container_name: spring-app
    image: spring-app
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: easy_eng
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 15
volumes:
  db-data:
    driver: local

